# Generated by Django 6.0.3 on 2026-03-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sale_price_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='VD: 100ml, 50ml, Màu đỏ...', max_length=100, verbose_name='Tên biến thể')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá (nếu khác giá gốc)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Tồn kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='variants/', verbose_name='Ảnh riêng (nếu có)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
            },
        ),
    ]
