# Generated by Django 6.0.3 on 2026-03-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productvariant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_id_2abda1_idx',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(help_text='VD: 100ml, Màu đỏ...', max_length=100, verbose_name='Tên biến thể'),
        ),
    ]
