# Generated by Django 6.0.3 on 2026-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_store_produ_id_2abda1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Dùng để tính phí vận chuyển', verbose_name='Cân nặng (gram)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Nếu để trống sẽ lấy từ sản phẩm gốc', verbose_name='Cân nặng (gram)'),
        ),
    ]
