# Generated by Django 6.0.3 on 2026-04-13 09:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_weight_productvariant_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Tiêu đề')),
                ('comment', models.TextField(verbose_name='Nội dung bình luận')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Ảnh đính kèm')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Đã mua hàng')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'verbose_name_plural': 'Đánh giá sản phẩm',
                'ordering': ['-created'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
