# Generated by Django 6.0.3 on 2026-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí vận chuyển'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Tổng tiền (đã bao gồm phí ship)'),
        ),
    ]
